spring:
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/middleearth
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        hibernate:
            ddl-auto: update

app:
    url: http://localhost:8080/

jwt:
    secret: MTIzNDU2Nzg=Bronze5

dozer:
    mapping-files: classpath:mapping.xml

bearerToken: AAAAAAAAAAAAAAAAAAAAAMsHdAEAAAAASeNVKpiQ388VrvJqsd8L97TGDjk%3DpaKlbasR2lfzbokiH2GnlGU3EhsteB5gYcy6OdmpQdqAhnsDkd
